## AUTHOR:      AISK11
## LOCATION:    ~/.config/mpv/mpv.conf (0644)
## DESCRIPTION: MPV media player configuration file.
## SOURCES:     https://github.com/mpv-player/mpv
## - ARCH:      community/mpv

## Do not display cover art for audio.
audio-display=no
