## AUTHOR:      AISK11
## LOCATION:    ~/.config/keepassxc/keepassxc.ini (0644)
## DESCRIPTION: KeePassXC password manager configuration file.
## SOURCES:     https://keepassxc.org/
## - ARCH:      community/keepassxc

[General]
ConfigVersion=2

[GUI]
ApplicationTheme=dark
CompactMode=false
TrayIconAppearance=monochrome-light

[PasswordGenerator]
AdditionalChars=
AdvancedMode=true
Braces=true
Dashes=true
ExcludedChars=
Length=64
Logograms=true
Math=true
Punctuation=true
Quotes=true

[Security]
ClearClipboardTimeout=10
