## AUTHOR:      AISK11
## LOCATION:    ~/.config/polybar/config.ini (0644)
## DESCRIPTION: Polybar status bar configuration file.
## SOURCES:     https://github.com/polybar/polybar
## - ARCH:      community/polybar community/ttf-dejavu

[colors]
background    = "#282a36"
foreground    = "#f8f8f2"
black         = "#21222c"
red           = "#ff5555"
green         = "#50fa7b"
yellow        = "#f1fa8c"
blue          = "#bd93f9"
purple        = "#ff79c6"
cyan          = "#8be9fd'
white         = "#f8f8f2"
light-black   = "#6272a4"
light-red     = "#ff6e6e"
light-green   = "#69ff94"
light-yellow  = "#ffffa5"
light-blue    = "#d6acff"
light-purple  = "#ff92df"
light-cyan    = "#a4ffff"
light-white   = "#ffffff"

[bar/default]
## Monitor settings $(polybar -M | cut -d ':' -f 1).
monitor          = ""
monitor-fallback = ""
monitor-strict   = "false"
monitor-exact    = "true"

## Window Manager settings.
override-redirect = "false"

## Bar size, roundness and position.
width    = "100%"
height   = "2.5%"
radius   = "0px"
bottom   = "false"

## Bar colors.
foreground = "${colors.foreground}"
background = "${colors.background}"

## Bar fonts $(fc-list | cut -d ':' -f 2 | cut -d ',' -f 2 | sed 's/^\ //g').
font-0 = "DejaVuSansMono.ttf,size=11;0"
font-1 = "Font Awesome 6 Free Solid:size=11;0"
font-2 = "Font Awesome 6 Free Regular:size=11;0"
font-3 = "Font Awesome 6 Brands Regular:size=11;0"




line-size = 100
line-color = #f00


fixed-center="true"
offset-x = "0px"
offset-y = "0px"


modules-left = "i3"
modules-center = "date"
modules-right = "xkeyboard"

[module/i3]
type            = "internal/i3"
enable-click    = "true"
enable-scroll   = "false"
wrapping-scroll = "false"

ws-icon-0       = "1;"
ws-icon-1       = "2;"
ws-icon-2       = "3;"
ws-icon-3       = "4;"
ws-icon-4       = "5;"
ws-icon-5       = "6;"
ws-icon-6       = "7;?"
ws-icon-7       = "8;"
ws-icon-8       = "9;"
ws-icon-9       = "10;"
ws-icon-default = ""

;; Focused = Active workspace on focused monitor (label-state).
label-focused            = "%icon%"
label-focused-foreground = ${colors.light-yellow}
label-focused-padding    = 1

;; Visible = Active workspace on unfocused monitor (label-state).
label-visible            = "%icon%"
label-visible-foreground = ${colors.yellow}
label-visible-padding    = 1

;; Unfocused = Inactive workspace on any monitor (label-state).
label-unfocused            = "%icon%"
label-unfocused-foreground = ${colors.light-blue}
label-unfocused-padding    = 1

;; Urgent = Workspace with urgency hint set (label-state).
label-urgent            = "%icon%"
label-urgent-foreground = ${colors.light-red}
label-urgent-padding    = 1

;; Separator in between workspaces (label-state).
label-separator            = ""
label-separator-padding    = 0
label-separator-foreground = ${colors.foreground}

;; Resize mode (label-mode).
label-mode            = ""
label-mode-foreground = ${colors.red}
label-mode-padding    = 0

;; Formatting.
format = <label-state> <label-mode>

[module/date]
type = internal/date

;; Refresh rate (seconds).
interval = 1.0

;; Datetime.
date     = "%{F#f1fa8c} %{F#ffffa5}%Y-%m-%d %H:%M:%S %Z"
date-alt = "%{F#bd93f9} %{F#d6acff}%Y-%m-%dT%H:%M:%S%z"

;; Label.
label = "%date%"

;; Formatting.
format            = "<label>"

[module/xkeyboard]
type = internal/xkeyboard

;; Icons.
layout-icon-0 = us;%{F#f1fa8c} %{F#ffffa5}us
layout-icon-1 = sk;%{F#bd93f9} %{F#d6acff}sk

;; Label.
label-layout            = "%icon%"

;; Formatting.
format            = "<label-layout>"
